import { bankValue } from '../entities/elements.js';
import { showCustomAlert } from '../app.js';

export class Transfer {
    constructor(date, senderName, emailSender, value, recipientName, emailRecipient){
        this.date = date;
        this.senderName = senderName;
        this.emailSender = emailSender;
        this.value = value;
        this.recipientName = recipientName;
        this.emailRecipient = emailRecipient;
    }

    async checkEmailExist () {
        try {
            const response = await fetch('http://localhost:3000/users');

            if (!response.ok) {
                const errorData = await response.json(); // Tenta ler o corpo do erro para mais detalhes
                throw new Error(`Erro ao realizar a trasnferencia: ${response.status} - ${errorData.message || response.statusText}`);
            }

            const users = response.json();

            const emailFound = users.find(u => u.email && u.email === this.emailSender && this.emailRecipient);
            return !!emailFound // Retorna true se encontrar, false caso contrÃ¡rio
        } catch (error) {
            showCustomAlert('Erro na verificaÃ§Ã£o de usuario, verifique se o usuario jÃ¡ esta cadastrado.');
            console.error('Erro na verificaÃ§Ã£o de usuario, verifique se o usuario jÃ¡ esta cadastrado.', error);
            return true;
        }
    }

    async makeTransfer(){
        const transferData = {
            date: this.date,
            senderName: this.senderName,
            valueTransfer: this.value,
            recipientName: this.recipientName
        }

        try {
            const response = await fetch('http://localhost:3000/transfers', {
                method: "POST",
                headers: {
                    'Content-type': "application/json"
                },
                    body: JSON.stringify(transferData)
            });

            if (!response.ok) {
                const errorData = await response.json(); // Tenta ler o corpo do erro para mais detalhes
                throw new Error(`Erro ao realizar a trasnferencia: ${response.status} - ${errorData.message || response.statusText}`);
            }

            const result = await response.json();

            //ADICIONAR VERIFICAÃ‡ÃƒO SE EXISTEM OS USUARIOS CADASTRADOS
            this.checkEmailExist()
            
            console.log('TransferÃªncia realizada com sucesso:', result);
            showCustomAlert('TransferÃªncia realizada com sucesso! ðŸŽ‰'); // Feedback para o usuÃ¡rio
        } catch (error) {
            console.error('Falha ao realizar a transferÃªncia:', error);
            showCustomAlert(`Falha na transferÃªncia: ${error.message}`);
            throw error;
        }
    }
}